package sn.ouznoreyni.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class InscriptionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInscriptionAllPropertiesEquals(Inscription expected, Inscription actual) {
        assertInscriptionAutoGeneratedPropertiesEquals(expected, actual);
        assertInscriptionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInscriptionAllUpdatablePropertiesEquals(Inscription expected, Inscription actual) {
        assertInscriptionUpdatableFieldsEquals(expected, actual);
        assertInscriptionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInscriptionAutoGeneratedPropertiesEquals(Inscription expected, Inscription actual) {
        assertThat(expected)
            .as("Verify Inscription auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInscriptionUpdatableFieldsEquals(Inscription expected, Inscription actual) {
        assertThat(expected)
            .as("Verify Inscription relevant properties")
            .satisfies(e -> assertThat(e.getDateInscription()).as("check dateInscription").isEqualTo(actual.getDateInscription()))
            .satisfies(e -> assertThat(e.getStatut()).as("check statut").isEqualTo(actual.getStatut()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInscriptionUpdatableRelationshipsEquals(Inscription expected, Inscription actual) {
        assertThat(expected)
            .as("Verify Inscription relationships")
            .satisfies(e -> assertThat(e.getEtudiant()).as("check etudiant").isEqualTo(actual.getEtudiant()))
            .satisfies(e -> assertThat(e.getCours()).as("check cours").isEqualTo(actual.getCours()));
    }
}
