package sn.ouznoreyni.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProfesseurAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfesseurAllPropertiesEquals(Professeur expected, Professeur actual) {
        assertProfesseurAutoGeneratedPropertiesEquals(expected, actual);
        assertProfesseurAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfesseurAllUpdatablePropertiesEquals(Professeur expected, Professeur actual) {
        assertProfesseurUpdatableFieldsEquals(expected, actual);
        assertProfesseurUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfesseurAutoGeneratedPropertiesEquals(Professeur expected, Professeur actual) {
        assertThat(expected)
            .as("Verify Professeur auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfesseurUpdatableFieldsEquals(Professeur expected, Professeur actual) {
        assertThat(expected)
            .as("Verify Professeur relevant properties")
            .satisfies(e -> assertThat(e.getNumeroEmploye()).as("check numeroEmploye").isEqualTo(actual.getNumeroEmploye()))
            .satisfies(e -> assertThat(e.getDateEmbauche()).as("check dateEmbauche").isEqualTo(actual.getDateEmbauche()))
            .satisfies(e -> assertThat(e.getSpecialite()).as("check specialite").isEqualTo(actual.getSpecialite()))
            .satisfies(e -> assertThat(e.getBureau()).as("check bureau").isEqualTo(actual.getBureau()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfesseurUpdatableRelationshipsEquals(Professeur expected, Professeur actual) {
        assertThat(expected)
            .as("Verify Professeur relationships")
            .satisfies(e -> assertThat(e.getDepartement()).as("check departement").isEqualTo(actual.getDepartement()));
    }
}
